### ISSUE TITLE
Your experience with Doodle?

### ISSUE THREAD

**Issue by pusolito** [Daniel5055/routle#1]
I saw that you tried Doodle in the Kotlin version, but switched to Next.js. I’m curious to hear your experience with Doodle and what made you switch.

**Comment by Daniel5055** [comment]
@pusolito I originally wrote my app in Java with Swing and wanted to bring it to the web. I used Kotlin due to its similarity to Java and that it supported writing web apps. Among the possible Kotlin/Js frameworks, I chose Doodle as I preferred its syntax the most and it was relatively well-documented.

Doodle in general was quite good when I used it. It had a good guide for starting and so I managed to get some stuff up pretty quickly. The tutorials on the documentation website were also good examples yet there were quite a step up from the getting started guide. However it took quite a while for me to fully understand the important concepts such as layouts and behaviors and I found myself often reading through the source code to understand. Once I did understand them though they were quite powerful tools.

Overall, I switched for mainly 3 reasons, most of which are not Doodle's fault:

1. Any changes I made to the frontend needed to be compiled to JavaScript which could take upwards of 30 seconds, which really slowed down my development.
2. I wanted to host my static website easily for free and NextJs with Vercel offered this.
3. Although JavaScript and CSS can be a pain, they do typically express things more concisely than Doodle could.

After the switch to NextJs however, I did come to appreciate how simple Doodle made formatting though. I could express exactly where I wanted things using Layouts whilst in JavaScript and CSS I would suffer for hours trying to make two `divs` the same dynamic size. 

Rendering shapes and images with Doodle was also much easier than in JavaScript `canvas` and `img` tags. Also the new 3D capabilities look cool as well now.

Overall, those were my thoughts on Doodle as far as I can remember, hope that helps.

**Comment by pusolito** [comment]
This is super helpful. Sorry to hear about the long build times. Things did get better with Kotlin 1.7.X. I see single digit build times that are manageable when coupled with the [continuous deployment](https://kotlinlang.org/docs/dev-server-continuous-compilation.html). But unlikely to rival the JS pipeline.

I'm glad to hear the docs helped. I'm also considering making the code for the apps within the docs available, since that will help with initial comprehension.

Thanks for taking the time to share your thoughts. I hope you find a suitable project to try it out with again.
